info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-24T09:13:18.271Z"}
info: Connected to the database. {"timestamp":"2022-05-24T09:13:23.271Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-24T10:48:54.911Z"}
info: Connected to the database. {"timestamp":"2022-05-24T10:48:57.816Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-24T12:07:01.085Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-24T12:07:29.472Z"}
info: Connected to the database. {"timestamp":"2022-05-24T12:07:33.183Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-24T14:15:19.134Z"}
info: Connected to the database. {"timestamp":"2022-05-24T14:15:23.827Z"}
error: 
      status - 400
      message - Authorization token is required 
      url - /api/v1/users/getAllUsers 
      method - GET 
      IP - ::1
     {"timestamp":"2022-05-24T15:05:34.098Z"}
error: 
    status - 500 
    message - ValidationError: "name" is required 
    url - /api/v1/users 
    method - POST 
    IP - ::1
   {"timestamp":"2022-05-24T15:06:45.249Z"}
error: 
    status - 500 
    message - ValidationError: "name" is required 
    url - /api/v1/users// 
    method - POST 
    IP - ::1
   {"timestamp":"2022-05-24T15:07:52.332Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-24T18:46:54.918Z"}
info: Connected to the database. {"timestamp":"2022-05-24T18:46:59.577Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-25T02:18:21.361Z"}
info: Connected to the database. {"timestamp":"2022-05-25T02:18:25.672Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-25T02:36:36.428Z"}
info: Connected to the database. {"timestamp":"2022-05-25T02:36:39.638Z"}
error: 
    status - 500 
    message - ValidationError: "name" is required 
    url - /api/v1/user 
    method - POST 
    IP - ::1
   {"timestamp":"2022-05-25T02:39:18.130Z"}
error: 
    status - 500 
    message - ValidationError: "name" is required 
    url - /api/v1/user 
    method - POST 
    IP - ::1
   {"timestamp":"2022-05-25T02:39:32.180Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-25T02:53:05.423Z"}
info: Connected to the database. {"timestamp":"2022-05-25T02:53:08.553Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-25T02:59:07.808Z"}
info: Connected to the database. {"timestamp":"2022-05-25T02:59:11.371Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-25T04:10:42.477Z"}
error: Could not connect to the database. connect ECONNREFUSED ::1:27017 {"reason":{"commonWireVersion":null,"compatibilityError":null,"compatible":true,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"logicalSessionTimeoutMinutes":null,"maxElectionId":null,"maxSetVersion":null,"servers":{},"setName":null,"stale":false,"type":"Single"},"stack":"MongooseServerSelectionError: connect ECONNREFUSED ::1:27017\n    at NativeConnection.Connection.openUri (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\connection.js:847:32)\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\index.js:351:10\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:32:5\n    at new Promise (<anonymous>)\n    at promiseOrCallback (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:31:10)\n    at Mongoose._promiseOrCallback (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\index.js:1149:10)\n    at Mongoose.connect (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\index.js:350:20)\n    at _callee$ (C:\\Users\\91809\\Desktop\\MyFirstProject\\src\\config\\/database.js:12:20)\n    at tryCatch (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:86:17)\n    at Generator._invoke (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:66:24)\n    at Generator.next (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:117:21)\n    at asyncGeneratorStep (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:3:24)\n    at _next (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:25:9)\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:32:7\n    at new Promise (<anonymous>)\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:21:12","timestamp":"2022-05-25T04:11:12.608Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-25T04:14:55.856Z"}
error: Could not connect to the database. connect ECONNREFUSED ::1:27017 {"reason":{"commonWireVersion":null,"compatibilityError":null,"compatible":true,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"logicalSessionTimeoutMinutes":null,"maxElectionId":null,"maxSetVersion":null,"servers":{},"setName":null,"stale":false,"type":"Single"},"stack":"MongooseServerSelectionError: connect ECONNREFUSED ::1:27017\n    at NativeConnection.Connection.openUri (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\connection.js:847:32)\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\index.js:351:10\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:32:5\n    at new Promise (<anonymous>)\n    at promiseOrCallback (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:31:10)\n    at Mongoose._promiseOrCallback (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\index.js:1149:10)\n    at Mongoose.connect (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\index.js:350:20)\n    at _callee$ (C:\\Users\\91809\\Desktop\\MyFirstProject\\src\\config\\/database.js:12:20)\n    at tryCatch (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:86:17)\n    at Generator._invoke (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:66:24)\n    at Generator.next (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:117:21)\n    at asyncGeneratorStep (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:3:24)\n    at _next (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:25:9)\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:32:7\n    at new Promise (<anonymous>)\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:21:12","timestamp":"2022-05-25T04:15:25.884Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-25T04:19:05.812Z"}
error: Could not connect to the database. connect ECONNREFUSED ::1:27017 {"reason":{"commonWireVersion":null,"compatibilityError":null,"compatible":true,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"logicalSessionTimeoutMinutes":null,"maxElectionId":null,"maxSetVersion":null,"servers":{},"setName":null,"stale":false,"type":"Single"},"stack":"MongooseServerSelectionError: connect ECONNREFUSED ::1:27017\n    at NativeConnection.Connection.openUri (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\connection.js:847:32)\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\index.js:351:10\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:32:5\n    at new Promise (<anonymous>)\n    at promiseOrCallback (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:31:10)\n    at Mongoose._promiseOrCallback (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\index.js:1149:10)\n    at Mongoose.connect (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\index.js:350:20)\n    at _callee$ (C:\\Users\\91809\\Desktop\\MyFirstProject\\src\\config\\/database.js:12:20)\n    at tryCatch (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:86:17)\n    at Generator._invoke (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:66:24)\n    at Generator.next (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:117:21)\n    at asyncGeneratorStep (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:3:24)\n    at _next (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:25:9)\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:32:7\n    at new Promise (<anonymous>)\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:21:12","timestamp":"2022-05-25T04:19:35.828Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-25T04:22:23.346Z"}
error: Could not connect to the database. connect ECONNREFUSED ::1:27017 {"reason":{"commonWireVersion":null,"compatibilityError":null,"compatible":true,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"logicalSessionTimeoutMinutes":null,"maxElectionId":null,"maxSetVersion":null,"servers":{},"setName":null,"stale":false,"type":"Single"},"stack":"MongooseServerSelectionError: connect ECONNREFUSED ::1:27017\n    at NativeConnection.Connection.openUri (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\connection.js:847:32)\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\index.js:351:10\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:32:5\n    at new Promise (<anonymous>)\n    at promiseOrCallback (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:31:10)\n    at Mongoose._promiseOrCallback (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\index.js:1149:10)\n    at Mongoose.connect (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\index.js:350:20)\n    at _callee$ (C:\\Users\\91809\\Desktop\\MyFirstProject\\src\\config\\/database.js:12:20)\n    at tryCatch (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:86:17)\n    at Generator._invoke (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:66:24)\n    at Generator.next (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:117:21)\n    at asyncGeneratorStep (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:3:24)\n    at _next (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:25:9)\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:32:7\n    at new Promise (<anonymous>)\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:21:12","timestamp":"2022-05-25T04:22:53.804Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-25T04:30:40.178Z"}
info: Connected to the database. {"timestamp":"2022-05-25T04:30:43.871Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-25T05:58:40.558Z"}
error: Could not connect to the database. connect ECONNREFUSED ::1:27017 {"reason":{"commonWireVersion":null,"compatibilityError":null,"compatible":true,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"logicalSessionTimeoutMinutes":null,"maxElectionId":null,"maxSetVersion":null,"servers":{},"setName":null,"stale":false,"type":"Single"},"stack":"MongooseServerSelectionError: connect ECONNREFUSED ::1:27017\n    at NativeConnection.Connection.openUri (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\connection.js:847:32)\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\index.js:351:10\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:32:5\n    at new Promise (<anonymous>)\n    at promiseOrCallback (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:31:10)\n    at Mongoose._promiseOrCallback (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\index.js:1149:10)\n    at Mongoose.connect (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\index.js:350:20)\n    at _callee$ (C:\\Users\\91809\\Desktop\\MyFirstProject\\src\\config\\/database.js:12:20)\n    at tryCatch (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:86:17)\n    at Generator._invoke (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:66:24)\n    at Generator.next (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:117:21)\n    at asyncGeneratorStep (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:3:24)\n    at _next (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:25:9)\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:32:7\n    at new Promise (<anonymous>)\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:21:12","timestamp":"2022-05-25T05:59:10.576Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-25T06:00:21.996Z"}
error: Could not connect to the database. connect ECONNREFUSED ::1:27017 {"reason":{"commonWireVersion":null,"compatibilityError":null,"compatible":true,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"logicalSessionTimeoutMinutes":null,"maxElectionId":null,"maxSetVersion":null,"servers":{},"setName":null,"stale":false,"type":"Single"},"stack":"MongooseServerSelectionError: connect ECONNREFUSED ::1:27017\n    at NativeConnection.Connection.openUri (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\connection.js:847:32)\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\index.js:351:10\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:32:5\n    at new Promise (<anonymous>)\n    at promiseOrCallback (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:31:10)\n    at Mongoose._promiseOrCallback (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\index.js:1149:10)\n    at Mongoose.connect (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\index.js:350:20)\n    at _callee$ (C:\\Users\\91809\\Desktop\\MyFirstProject\\src\\config\\/database.js:12:20)\n    at tryCatch (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:86:17)\n    at Generator._invoke (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:66:24)\n    at Generator.next (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:117:21)\n    at asyncGeneratorStep (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:3:24)\n    at _next (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:25:9)\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:32:7\n    at new Promise (<anonymous>)\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:21:12","timestamp":"2022-05-25T06:00:52.012Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-25T06:02:53.502Z"}
info: Connected to the database. {"timestamp":"2022-05-25T06:02:56.873Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-25T06:03:47.850Z"}
error: Could not connect to the database. connect ECONNREFUSED ::1:27017 {"reason":{"commonWireVersion":null,"compatibilityError":null,"compatible":true,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"logicalSessionTimeoutMinutes":null,"maxElectionId":null,"maxSetVersion":null,"servers":{},"setName":null,"stale":false,"type":"Single"},"stack":"MongooseServerSelectionError: connect ECONNREFUSED ::1:27017\n    at NativeConnection.Connection.openUri (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\connection.js:847:32)\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\index.js:351:10\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:32:5\n    at new Promise (<anonymous>)\n    at promiseOrCallback (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:31:10)\n    at Mongoose._promiseOrCallback (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\index.js:1149:10)\n    at Mongoose.connect (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\index.js:350:20)\n    at _callee$ (C:\\Users\\91809\\Desktop\\MyFirstProject\\src\\config\\/database.js:12:20)\n    at tryCatch (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:86:17)\n    at Generator._invoke (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:66:24)\n    at Generator.next (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:117:21)\n    at asyncGeneratorStep (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:3:24)\n    at _next (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:25:9)\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:32:7\n    at new Promise (<anonymous>)\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:21:12","timestamp":"2022-05-25T06:04:17.871Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-25T06:05:17.519Z"}
error: Could not connect to the database. connect ECONNREFUSED ::1:27017 {"reason":{"commonWireVersion":null,"compatibilityError":null,"compatible":true,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"logicalSessionTimeoutMinutes":null,"maxElectionId":null,"maxSetVersion":null,"servers":{},"setName":null,"stale":false,"type":"Single"},"stack":"MongooseServerSelectionError: connect ECONNREFUSED ::1:27017\n    at NativeConnection.Connection.openUri (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\connection.js:847:32)\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\index.js:351:10\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:32:5\n    at new Promise (<anonymous>)\n    at promiseOrCallback (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:31:10)\n    at Mongoose._promiseOrCallback (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\index.js:1149:10)\n    at Mongoose.connect (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\index.js:350:20)\n    at _callee$ (C:\\Users\\91809\\Desktop\\MyFirstProject\\src\\config\\/database.js:12:20)\n    at tryCatch (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:86:17)\n    at Generator._invoke (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:66:24)\n    at Generator.next (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:117:21)\n    at asyncGeneratorStep (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:3:24)\n    at _next (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:25:9)\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:32:7\n    at new Promise (<anonymous>)\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:21:12","timestamp":"2022-05-25T06:05:47.469Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-25T06:06:52.694Z"}
error: Could not connect to the database. connect ECONNREFUSED ::1:27017 {"reason":{"commonWireVersion":null,"compatibilityError":null,"compatible":true,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"logicalSessionTimeoutMinutes":null,"maxElectionId":null,"maxSetVersion":null,"servers":{},"setName":null,"stale":false,"type":"Single"},"stack":"MongooseServerSelectionError: connect ECONNREFUSED ::1:27017\n    at NativeConnection.Connection.openUri (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\connection.js:847:32)\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\index.js:351:10\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:32:5\n    at new Promise (<anonymous>)\n    at promiseOrCallback (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:31:10)\n    at Mongoose._promiseOrCallback (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\index.js:1149:10)\n    at Mongoose.connect (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\index.js:350:20)\n    at _callee$ (C:\\Users\\91809\\Desktop\\MyFirstProject\\src\\config\\/database.js:12:20)\n    at tryCatch (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:86:17)\n    at Generator._invoke (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:66:24)\n    at Generator.next (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:117:21)\n    at asyncGeneratorStep (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:3:24)\n    at _next (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:25:9)\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:32:7\n    at new Promise (<anonymous>)\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:21:12","timestamp":"2022-05-25T06:07:22.833Z"}
error: 
    status - 500 
    message - MongooseError: Operation `users.insertOne()` buffering timed out after 10000ms
    at Timeout.<anonymous> (C:\Users\91809\Desktop\MyFirstProject\node_modules\mongoose\lib\drivers\node-mongodb-native\collection.js:198:23)
    at listOnTimeout (node:internal/timers:564:17)
    at processTimers (node:internal/timers:507:7) 
    url - /api/v1/users 
    method - POST 
    IP - ::1
   {"timestamp":"2022-05-25T06:07:23.496Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-25T06:09:20.887Z"}
info: Connected to the database. {"timestamp":"2022-05-25T06:09:24.560Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-25T06:11:48.308Z"}
error: Could not connect to the database. connect ECONNREFUSED ::1:27017 {"reason":{"commonWireVersion":null,"compatibilityError":null,"compatible":true,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"logicalSessionTimeoutMinutes":null,"maxElectionId":null,"maxSetVersion":null,"servers":{},"setName":null,"stale":false,"type":"Single"},"stack":"MongooseServerSelectionError: connect ECONNREFUSED ::1:27017\n    at NativeConnection.Connection.openUri (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\connection.js:847:32)\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\index.js:351:10\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:32:5\n    at new Promise (<anonymous>)\n    at promiseOrCallback (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:31:10)\n    at Mongoose._promiseOrCallback (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\index.js:1149:10)\n    at Mongoose.connect (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\index.js:350:20)\n    at _callee$ (C:\\Users\\91809\\Desktop\\MyFirstProject\\src\\config\\/database.js:12:20)\n    at tryCatch (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:86:17)\n    at Generator._invoke (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:66:24)\n    at Generator.next (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:117:21)\n    at asyncGeneratorStep (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:3:24)\n    at _next (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:25:9)\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:32:7\n    at new Promise (<anonymous>)\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:21:12","timestamp":"2022-05-25T06:12:18.323Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-25T06:14:39.318Z"}
error: Could not connect to the database. connect ECONNREFUSED ::1:27017 {"reason":{"commonWireVersion":null,"compatibilityError":null,"compatible":true,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"logicalSessionTimeoutMinutes":null,"maxElectionId":null,"maxSetVersion":null,"servers":{},"setName":null,"stale":false,"type":"Single"},"stack":"MongooseServerSelectionError: connect ECONNREFUSED ::1:27017\n    at NativeConnection.Connection.openUri (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\connection.js:847:32)\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\index.js:351:10\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:32:5\n    at new Promise (<anonymous>)\n    at promiseOrCallback (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:31:10)\n    at Mongoose._promiseOrCallback (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\index.js:1149:10)\n    at Mongoose.connect (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\index.js:350:20)\n    at _callee$ (C:\\Users\\91809\\Desktop\\MyFirstProject\\src\\config\\/database.js:12:20)\n    at tryCatch (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:86:17)\n    at Generator._invoke (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:66:24)\n    at Generator.next (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:117:21)\n    at asyncGeneratorStep (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:3:24)\n    at _next (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:25:9)\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:32:7\n    at new Promise (<anonymous>)\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:21:12","timestamp":"2022-05-25T06:15:09.332Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-25T06:21:35.005Z"}
error: Could not connect to the database. connect ECONNREFUSED ::1:27017 {"reason":{"commonWireVersion":null,"compatibilityError":null,"compatible":true,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"logicalSessionTimeoutMinutes":null,"maxElectionId":null,"maxSetVersion":null,"servers":{},"setName":null,"stale":false,"type":"Single"},"stack":"MongooseServerSelectionError: connect ECONNREFUSED ::1:27017\n    at NativeConnection.Connection.openUri (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\connection.js:847:32)\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\index.js:351:10\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:32:5\n    at new Promise (<anonymous>)\n    at promiseOrCallback (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:31:10)\n    at Mongoose._promiseOrCallback (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\index.js:1149:10)\n    at Mongoose.connect (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\index.js:350:20)\n    at _callee$ (C:\\Users\\91809\\Desktop\\MyFirstProject\\src\\config\\/database.js:12:20)\n    at tryCatch (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:86:17)\n    at Generator._invoke (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:66:24)\n    at Generator.next (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:117:21)\n    at asyncGeneratorStep (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:3:24)\n    at _next (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:25:9)\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:32:7\n    at new Promise (<anonymous>)\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:21:12","timestamp":"2022-05-25T06:22:05.024Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-25T06:26:42.230Z"}
error: Could not connect to the database. connect ECONNREFUSED ::1:27017 {"reason":{"commonWireVersion":null,"compatibilityError":null,"compatible":true,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"logicalSessionTimeoutMinutes":null,"maxElectionId":null,"maxSetVersion":null,"servers":{},"setName":null,"stale":false,"type":"Single"},"stack":"MongooseServerSelectionError: connect ECONNREFUSED ::1:27017\n    at NativeConnection.Connection.openUri (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\connection.js:847:32)\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\index.js:351:10\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:32:5\n    at new Promise (<anonymous>)\n    at promiseOrCallback (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:31:10)\n    at Mongoose._promiseOrCallback (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\index.js:1149:10)\n    at Mongoose.connect (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\index.js:350:20)\n    at _callee$ (C:\\Users\\91809\\Desktop\\MyFirstProject\\src\\config\\/database.js:12:20)\n    at tryCatch (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:86:17)\n    at Generator._invoke (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:66:24)\n    at Generator.next (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:117:21)\n    at asyncGeneratorStep (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:3:24)\n    at _next (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:25:9)\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:32:7\n    at new Promise (<anonymous>)\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:21:12","timestamp":"2022-05-25T06:27:12.243Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-25T06:30:01.772Z"}
error: Could not connect to the database. connect ECONNREFUSED ::1:27017 {"reason":{"commonWireVersion":null,"compatibilityError":null,"compatible":true,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"logicalSessionTimeoutMinutes":null,"maxElectionId":null,"maxSetVersion":null,"servers":{},"setName":null,"stale":false,"type":"Single"},"stack":"MongooseServerSelectionError: connect ECONNREFUSED ::1:27017\n    at NativeConnection.Connection.openUri (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\connection.js:847:32)\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\index.js:351:10\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:32:5\n    at new Promise (<anonymous>)\n    at promiseOrCallback (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:31:10)\n    at Mongoose._promiseOrCallback (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\index.js:1149:10)\n    at Mongoose.connect (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\index.js:350:20)\n    at _callee$ (C:\\Users\\91809\\Desktop\\MyFirstProject\\src\\config\\/database.js:12:20)\n    at tryCatch (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:86:17)\n    at Generator._invoke (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:66:24)\n    at Generator.next (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:117:21)\n    at asyncGeneratorStep (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:3:24)\n    at _next (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:25:9)\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:32:7\n    at new Promise (<anonymous>)\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:21:12","timestamp":"2022-05-25T06:30:31.793Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-25T06:32:07.562Z"}
error: Could not connect to the database. connect ECONNREFUSED ::1:27017 {"reason":{"commonWireVersion":null,"compatibilityError":null,"compatible":true,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"logicalSessionTimeoutMinutes":null,"maxElectionId":null,"maxSetVersion":null,"servers":{},"setName":null,"stale":false,"type":"Single"},"stack":"MongooseServerSelectionError: connect ECONNREFUSED ::1:27017\n    at NativeConnection.Connection.openUri (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\connection.js:847:32)\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\index.js:351:10\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:32:5\n    at new Promise (<anonymous>)\n    at promiseOrCallback (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:31:10)\n    at Mongoose._promiseOrCallback (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\index.js:1149:10)\n    at Mongoose.connect (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\index.js:350:20)\n    at _callee$ (C:\\Users\\91809\\Desktop\\MyFirstProject\\src\\config\\/database.js:12:20)\n    at tryCatch (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:86:17)\n    at Generator._invoke (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:66:24)\n    at Generator.next (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:117:21)\n    at asyncGeneratorStep (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:3:24)\n    at _next (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:25:9)\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:32:7\n    at new Promise (<anonymous>)\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:21:12","timestamp":"2022-05-25T06:32:37.585Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-25T06:36:42.103Z"}
error: Could not connect to the database. connect ECONNREFUSED ::1:27017 {"reason":{"commonWireVersion":null,"compatibilityError":null,"compatible":true,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"logicalSessionTimeoutMinutes":null,"maxElectionId":null,"maxSetVersion":null,"servers":{},"setName":null,"stale":false,"type":"Single"},"stack":"MongooseServerSelectionError: connect ECONNREFUSED ::1:27017\n    at NativeConnection.Connection.openUri (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\connection.js:847:32)\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\index.js:351:10\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:32:5\n    at new Promise (<anonymous>)\n    at promiseOrCallback (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:31:10)\n    at Mongoose._promiseOrCallback (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\index.js:1149:10)\n    at Mongoose.connect (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\index.js:350:20)\n    at _callee$ (C:\\Users\\91809\\Desktop\\MyFirstProject\\src\\config\\/database.js:12:20)\n    at tryCatch (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:86:17)\n    at Generator._invoke (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:66:24)\n    at Generator.next (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:117:21)\n    at asyncGeneratorStep (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:3:24)\n    at _next (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:25:9)\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:32:7\n    at new Promise (<anonymous>)\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:21:12","timestamp":"2022-05-25T06:37:12.120Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-25T06:38:11.782Z"}
info: Connected to the database. {"timestamp":"2022-05-25T06:38:15.626Z"}
error: 
      status - 400
      message - Authorization token is required 
      url - /api/v1/users/628dcf2a7e567213ecbe3b66 
      method - GET 
      IP - ::1
     {"timestamp":"2022-05-25T06:41:15.885Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-25T08:53:44.467Z"}
error: Could not connect to the database. connect ECONNREFUSED ::1:27017 {"reason":{"commonWireVersion":null,"compatibilityError":null,"compatible":true,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"logicalSessionTimeoutMinutes":null,"maxElectionId":null,"maxSetVersion":null,"servers":{},"setName":null,"stale":false,"type":"Single"},"stack":"MongooseServerSelectionError: connect ECONNREFUSED ::1:27017\n    at NativeConnection.Connection.openUri (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\connection.js:847:32)\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\index.js:351:10\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:32:5\n    at new Promise (<anonymous>)\n    at promiseOrCallback (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:31:10)\n    at Mongoose._promiseOrCallback (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\index.js:1149:10)\n    at Mongoose.connect (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\index.js:350:20)\n    at _callee$ (C:\\Users\\91809\\Desktop\\MyFirstProject\\src\\config\\/database.js:12:20)\n    at tryCatch (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:86:17)\n    at Generator._invoke (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:66:24)\n    at Generator.next (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:117:21)\n    at asyncGeneratorStep (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:3:24)\n    at _next (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:25:9)\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:32:7\n    at new Promise (<anonymous>)\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:21:12","timestamp":"2022-05-25T08:54:14.476Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-25T09:15:33.588Z"}
error: Could not connect to the database. connect ECONNREFUSED ::1:27017 {"reason":{"commonWireVersion":null,"compatibilityError":null,"compatible":true,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"logicalSessionTimeoutMinutes":null,"maxElectionId":null,"maxSetVersion":null,"servers":{},"setName":null,"stale":false,"type":"Single"},"stack":"MongooseServerSelectionError: connect ECONNREFUSED ::1:27017\n    at NativeConnection.Connection.openUri (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\connection.js:847:32)\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\index.js:351:10\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:32:5\n    at new Promise (<anonymous>)\n    at promiseOrCallback (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:31:10)\n    at Mongoose._promiseOrCallback (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\index.js:1149:10)\n    at Mongoose.connect (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\index.js:350:20)\n    at _callee$ (C:\\Users\\91809\\Desktop\\MyFirstProject\\src\\config\\/database.js:12:20)\n    at tryCatch (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:86:17)\n    at Generator._invoke (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:66:24)\n    at Generator.next (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:117:21)\n    at asyncGeneratorStep (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:3:24)\n    at _next (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:25:9)\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:32:7\n    at new Promise (<anonymous>)\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:21:12","timestamp":"2022-05-25T09:16:03.616Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-25T09:35:39.372Z"}
error: Could not connect to the database. connect ECONNREFUSED ::1:27017 {"reason":{"commonWireVersion":null,"compatibilityError":null,"compatible":true,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"logicalSessionTimeoutMinutes":null,"maxElectionId":null,"maxSetVersion":null,"servers":{},"setName":null,"stale":false,"type":"Single"},"stack":"MongooseServerSelectionError: connect ECONNREFUSED ::1:27017\n    at NativeConnection.Connection.openUri (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\connection.js:847:32)\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\index.js:351:10\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:32:5\n    at new Promise (<anonymous>)\n    at promiseOrCallback (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:31:10)\n    at Mongoose._promiseOrCallback (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\index.js:1149:10)\n    at Mongoose.connect (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\index.js:350:20)\n    at _callee$ (C:\\Users\\91809\\Desktop\\MyFirstProject\\src\\config\\/database.js:12:20)\n    at tryCatch (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:86:17)\n    at Generator._invoke (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:66:24)\n    at Generator.next (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:117:21)\n    at asyncGeneratorStep (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:3:24)\n    at _next (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:25:9)\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:32:7\n    at new Promise (<anonymous>)\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:21:12","timestamp":"2022-05-25T09:36:09.394Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-25T09:54:24.047Z"}
error: Could not connect to the database. connect ECONNREFUSED ::1:27017 {"reason":{"commonWireVersion":null,"compatibilityError":null,"compatible":true,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"logicalSessionTimeoutMinutes":null,"maxElectionId":null,"maxSetVersion":null,"servers":{},"setName":null,"stale":false,"type":"Single"},"stack":"MongooseServerSelectionError: connect ECONNREFUSED ::1:27017\n    at NativeConnection.Connection.openUri (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\connection.js:847:32)\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\index.js:351:10\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:32:5\n    at new Promise (<anonymous>)\n    at promiseOrCallback (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:31:10)\n    at Mongoose._promiseOrCallback (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\index.js:1149:10)\n    at Mongoose.connect (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\index.js:350:20)\n    at _callee$ (C:\\Users\\91809\\Desktop\\MyFirstProject\\src\\config\\/database.js:12:20)\n    at tryCatch (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:86:17)\n    at Generator._invoke (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:66:24)\n    at Generator.next (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:117:21)\n    at asyncGeneratorStep (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:3:24)\n    at _next (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:25:9)\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:32:7\n    at new Promise (<anonymous>)\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:21:12","timestamp":"2022-05-25T09:54:54.078Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-25T10:20:59.457Z"}
error: Could not connect to the database. connect ECONNREFUSED ::1:27017 {"reason":{"commonWireVersion":null,"compatibilityError":null,"compatible":true,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"logicalSessionTimeoutMinutes":null,"maxElectionId":null,"maxSetVersion":null,"servers":{},"setName":null,"stale":false,"type":"Single"},"stack":"MongooseServerSelectionError: connect ECONNREFUSED ::1:27017\n    at NativeConnection.Connection.openUri (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\connection.js:847:32)\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\index.js:351:10\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:32:5\n    at new Promise (<anonymous>)\n    at promiseOrCallback (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:31:10)\n    at Mongoose._promiseOrCallback (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\index.js:1149:10)\n    at Mongoose.connect (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\index.js:350:20)\n    at _callee$ (C:\\Users\\91809\\Desktop\\MyFirstProject\\src\\config\\/database.js:12:20)\n    at tryCatch (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:86:17)\n    at Generator._invoke (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:66:24)\n    at Generator.next (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:117:21)\n    at asyncGeneratorStep (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:3:24)\n    at _next (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:25:9)\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:32:7\n    at new Promise (<anonymous>)\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:21:12","timestamp":"2022-05-25T10:21:29.503Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-25T10:23:31.455Z"}
error: Could not connect to the database. connect ECONNREFUSED ::1:27017 {"reason":{"commonWireVersion":null,"compatibilityError":null,"compatible":true,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"logicalSessionTimeoutMinutes":null,"maxElectionId":null,"maxSetVersion":null,"servers":{},"setName":null,"stale":false,"type":"Single"},"stack":"MongooseServerSelectionError: connect ECONNREFUSED ::1:27017\n    at NativeConnection.Connection.openUri (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\connection.js:847:32)\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\index.js:351:10\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:32:5\n    at new Promise (<anonymous>)\n    at promiseOrCallback (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:31:10)\n    at Mongoose._promiseOrCallback (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\index.js:1149:10)\n    at Mongoose.connect (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\index.js:350:20)\n    at _callee$ (C:\\Users\\91809\\Desktop\\MyFirstProject\\src\\config\\/database.js:12:20)\n    at tryCatch (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:86:17)\n    at Generator._invoke (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:66:24)\n    at Generator.next (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:117:21)\n    at asyncGeneratorStep (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:3:24)\n    at _next (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:25:9)\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:32:7\n    at new Promise (<anonymous>)\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:21:12","timestamp":"2022-05-25T10:24:01.478Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-25T10:36:35.127Z"}
error: Could not connect to the database. connect ECONNREFUSED ::1:27017 {"reason":{"commonWireVersion":null,"compatibilityError":null,"compatible":true,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"logicalSessionTimeoutMinutes":null,"maxElectionId":null,"maxSetVersion":null,"servers":{},"setName":null,"stale":false,"type":"Single"},"stack":"MongooseServerSelectionError: connect ECONNREFUSED ::1:27017\n    at NativeConnection.Connection.openUri (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\connection.js:847:32)\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\index.js:351:10\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:32:5\n    at new Promise (<anonymous>)\n    at promiseOrCallback (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:31:10)\n    at Mongoose._promiseOrCallback (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\index.js:1149:10)\n    at Mongoose.connect (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\index.js:350:20)\n    at _callee$ (C:\\Users\\91809\\Desktop\\MyFirstProject\\src\\config\\/database.js:12:20)\n    at tryCatch (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:86:17)\n    at Generator._invoke (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:66:24)\n    at Generator.next (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:117:21)\n    at asyncGeneratorStep (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:3:24)\n    at _next (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:25:9)\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:32:7\n    at new Promise (<anonymous>)\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:21:12","timestamp":"2022-05-25T10:37:05.125Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-25T10:38:01.476Z"}
error: Could not connect to the database. connect ECONNREFUSED ::1:27017 {"reason":{"commonWireVersion":null,"compatibilityError":null,"compatible":true,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"logicalSessionTimeoutMinutes":null,"maxElectionId":null,"maxSetVersion":null,"servers":{},"setName":null,"stale":false,"type":"Single"},"stack":"MongooseServerSelectionError: connect ECONNREFUSED ::1:27017\n    at NativeConnection.Connection.openUri (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\connection.js:847:32)\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\index.js:351:10\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:32:5\n    at new Promise (<anonymous>)\n    at promiseOrCallback (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:31:10)\n    at Mongoose._promiseOrCallback (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\index.js:1149:10)\n    at Mongoose.connect (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\index.js:350:20)\n    at _callee$ (C:\\Users\\91809\\Desktop\\MyFirstProject\\src\\config\\/database.js:12:20)\n    at tryCatch (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:86:17)\n    at Generator._invoke (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:66:24)\n    at Generator.next (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:117:21)\n    at asyncGeneratorStep (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:3:24)\n    at _next (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:25:9)\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:32:7\n    at new Promise (<anonymous>)\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:21:12","timestamp":"2022-05-25T10:38:31.500Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-25T10:40:36.133Z"}
info: Connected to the database. {"timestamp":"2022-05-25T10:40:39.089Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-25T10:46:58.489Z"}
error: Could not connect to the database. connect ECONNREFUSED ::1:27017 {"reason":{"commonWireVersion":null,"compatibilityError":null,"compatible":true,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"logicalSessionTimeoutMinutes":null,"maxElectionId":null,"maxSetVersion":null,"servers":{},"setName":null,"stale":false,"type":"Single"},"stack":"MongooseServerSelectionError: connect ECONNREFUSED ::1:27017\n    at NativeConnection.Connection.openUri (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\connection.js:847:32)\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\index.js:351:10\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:32:5\n    at new Promise (<anonymous>)\n    at promiseOrCallback (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:31:10)\n    at Mongoose._promiseOrCallback (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\index.js:1149:10)\n    at Mongoose.connect (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\index.js:350:20)\n    at _callee$ (C:\\Users\\91809\\Desktop\\MyFirstProject\\src\\config\\/database.js:12:20)\n    at tryCatch (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:86:17)\n    at Generator._invoke (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:66:24)\n    at Generator.next (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:117:21)\n    at asyncGeneratorStep (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:3:24)\n    at _next (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:25:9)\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:32:7\n    at new Promise (<anonymous>)\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:21:12","timestamp":"2022-05-25T10:47:28.503Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-25T10:48:50.461Z"}
info: Connected to the database. {"timestamp":"2022-05-25T10:48:53.188Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-25T10:53:11.784Z"}
info: Connected to the database. {"timestamp":"2022-05-25T10:53:14.587Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-25T10:55:33.581Z"}
error: Could not connect to the database. connect ECONNREFUSED ::1:27017 {"reason":{"commonWireVersion":null,"compatibilityError":null,"compatible":true,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"logicalSessionTimeoutMinutes":null,"maxElectionId":null,"maxSetVersion":null,"servers":{},"setName":null,"stale":false,"type":"Single"},"stack":"MongooseServerSelectionError: connect ECONNREFUSED ::1:27017\n    at NativeConnection.Connection.openUri (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\connection.js:847:32)\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\index.js:351:10\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:32:5\n    at new Promise (<anonymous>)\n    at promiseOrCallback (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:31:10)\n    at Mongoose._promiseOrCallback (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\index.js:1149:10)\n    at Mongoose.connect (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\index.js:350:20)\n    at _callee$ (C:\\Users\\91809\\Desktop\\MyFirstProject\\src\\config\\/database.js:12:20)\n    at tryCatch (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:86:17)\n    at Generator._invoke (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:66:24)\n    at Generator.next (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:117:21)\n    at asyncGeneratorStep (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:3:24)\n    at _next (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:25:9)\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:32:7\n    at new Promise (<anonymous>)\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:21:12","timestamp":"2022-05-25T10:56:03.572Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-25T10:56:57.341Z"}
info: Connected to the database. {"timestamp":"2022-05-25T10:57:00.127Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-25T10:57:54.366Z"}
error: 
    status - 500 
    message - MongooseError: Operation `users.findOneAndUpdate()` buffering timed out after 10000ms
    at Timeout.<anonymous> (C:\Users\91809\Desktop\MyFirstProject\node_modules\mongoose\lib\drivers\node-mongodb-native\collection.js:198:23)
    at listOnTimeout (node:internal/timers:564:17)
    at processTimers (node:internal/timers:507:7) 
    url - /api/v1/users/628e0a3d2ee2641c147c3bc2 
    method - PUT 
    IP - ::1
   {"timestamp":"2022-05-25T10:58:19.422Z"}
error: Could not connect to the database. connect ECONNREFUSED ::1:27017 {"reason":{"commonWireVersion":null,"compatibilityError":null,"compatible":true,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"logicalSessionTimeoutMinutes":null,"maxElectionId":null,"maxSetVersion":null,"servers":{},"setName":null,"stale":false,"type":"Single"},"stack":"MongooseServerSelectionError: connect ECONNREFUSED ::1:27017\n    at NativeConnection.Connection.openUri (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\connection.js:847:32)\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\index.js:351:10\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:32:5\n    at new Promise (<anonymous>)\n    at promiseOrCallback (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:31:10)\n    at Mongoose._promiseOrCallback (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\index.js:1149:10)\n    at Mongoose.connect (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\index.js:350:20)\n    at _callee$ (C:\\Users\\91809\\Desktop\\MyFirstProject\\src\\config\\/database.js:12:20)\n    at tryCatch (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:86:17)\n    at Generator._invoke (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:66:24)\n    at Generator.next (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:117:21)\n    at asyncGeneratorStep (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:3:24)\n    at _next (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:25:9)\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:32:7\n    at new Promise (<anonymous>)\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:21:12","timestamp":"2022-05-25T10:58:24.392Z"}
error: 
    status - 500 
    message - MongooseError: Operation `users.findOneAndUpdate()` buffering timed out after 10000ms
    at Timeout.<anonymous> (C:\Users\91809\Desktop\MyFirstProject\node_modules\mongoose\lib\drivers\node-mongodb-native\collection.js:198:23)
    at listOnTimeout (node:internal/timers:564:17)
    at processTimers (node:internal/timers:507:7) 
    url - /api/v1/users/628e0a3d2ee2641c147c3bc2 
    method - PUT 
    IP - ::1
   {"timestamp":"2022-05-25T10:58:55.053Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-25T11:00:05.503Z"}
info: Connected to the database. {"timestamp":"2022-05-25T11:00:08.240Z"}
error: 
      status - 400
      message - Authorization token is required 
      url - /api/v1/users/628dcf187e567213ecbe3b64 
      method - GET 
      IP - ::1
     {"timestamp":"2022-05-25T11:03:09.094Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-25T11:41:50.559Z"}
error: Could not connect to the database. connect ECONNREFUSED ::1:27017 {"reason":{"commonWireVersion":null,"compatibilityError":null,"compatible":true,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"logicalSessionTimeoutMinutes":null,"maxElectionId":null,"maxSetVersion":null,"servers":{},"setName":null,"stale":false,"type":"Single"},"stack":"MongooseServerSelectionError: connect ECONNREFUSED ::1:27017\n    at NativeConnection.Connection.openUri (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\connection.js:847:32)\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\index.js:351:10\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:32:5\n    at new Promise (<anonymous>)\n    at promiseOrCallback (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:31:10)\n    at Mongoose._promiseOrCallback (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\index.js:1149:10)\n    at Mongoose.connect (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\index.js:350:20)\n    at _callee$ (C:\\Users\\91809\\Desktop\\MyFirstProject\\src\\config\\/database.js:12:20)\n    at tryCatch (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:86:17)\n    at Generator._invoke (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:66:24)\n    at Generator.next (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:117:21)\n    at asyncGeneratorStep (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:3:24)\n    at _next (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:25:9)\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:32:7\n    at new Promise (<anonymous>)\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:21:12","timestamp":"2022-05-25T11:42:20.576Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-26T02:19:57.963Z"}
info: Connected to the database. {"timestamp":"2022-05-26T02:20:02.748Z"}
error: 
      status - 400
      message - Authorization token is required 
      url - /api/v1/users/628dcf187e567213ecbe3b64 
      method - GET 
      IP - ::1
     {"timestamp":"2022-05-26T02:24:22.362Z"}
error: 
      status - 400
      message - Authorization token is required 
      url - /api/v1/users/628eea450fa00621a44167e0 
      method - GET 
      IP - ::1
     {"timestamp":"2022-05-26T02:48:52.843Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-26T02:50:23.432Z"}
info: Connected to the database. {"timestamp":"2022-05-26T02:50:29.519Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-26T02:52:50.781Z"}
info: Connected to the database. {"timestamp":"2022-05-26T02:52:55.066Z"}
