error: 
      status - 400
      message - Authorization token is required 
      url - /api/v1/users/getAllUsers 
      method - GET 
      IP - ::1
     {"timestamp":"2022-05-24T15:05:34.098Z"}
error: 
    status - 500 
    message - ValidationError: "name" is required 
    url - /api/v1/users 
    method - POST 
    IP - ::1
   {"timestamp":"2022-05-24T15:06:45.249Z"}
error: 
    status - 500 
    message - ValidationError: "name" is required 
    url - /api/v1/users// 
    method - POST 
    IP - ::1
   {"timestamp":"2022-05-24T15:07:52.332Z"}
error: 
    status - 500 
    message - ValidationError: "name" is required 
    url - /api/v1/user 
    method - POST 
    IP - ::1
   {"timestamp":"2022-05-25T02:39:18.130Z"}
error: 
    status - 500 
    message - ValidationError: "name" is required 
    url - /api/v1/user 
    method - POST 
    IP - ::1
   {"timestamp":"2022-05-25T02:39:32.180Z"}
error: Could not connect to the database. connect ECONNREFUSED ::1:27017 {"reason":{"commonWireVersion":null,"compatibilityError":null,"compatible":true,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"logicalSessionTimeoutMinutes":null,"maxElectionId":null,"maxSetVersion":null,"servers":{},"setName":null,"stale":false,"type":"Single"},"stack":"MongooseServerSelectionError: connect ECONNREFUSED ::1:27017\n    at NativeConnection.Connection.openUri (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\connection.js:847:32)\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\index.js:351:10\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:32:5\n    at new Promise (<anonymous>)\n    at promiseOrCallback (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:31:10)\n    at Mongoose._promiseOrCallback (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\index.js:1149:10)\n    at Mongoose.connect (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\index.js:350:20)\n    at _callee$ (C:\\Users\\91809\\Desktop\\MyFirstProject\\src\\config\\/database.js:12:20)\n    at tryCatch (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:86:17)\n    at Generator._invoke (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:66:24)\n    at Generator.next (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:117:21)\n    at asyncGeneratorStep (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:3:24)\n    at _next (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:25:9)\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:32:7\n    at new Promise (<anonymous>)\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:21:12","timestamp":"2022-05-25T04:11:12.608Z"}
error: Could not connect to the database. connect ECONNREFUSED ::1:27017 {"reason":{"commonWireVersion":null,"compatibilityError":null,"compatible":true,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"logicalSessionTimeoutMinutes":null,"maxElectionId":null,"maxSetVersion":null,"servers":{},"setName":null,"stale":false,"type":"Single"},"stack":"MongooseServerSelectionError: connect ECONNREFUSED ::1:27017\n    at NativeConnection.Connection.openUri (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\connection.js:847:32)\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\index.js:351:10\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:32:5\n    at new Promise (<anonymous>)\n    at promiseOrCallback (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:31:10)\n    at Mongoose._promiseOrCallback (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\index.js:1149:10)\n    at Mongoose.connect (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\index.js:350:20)\n    at _callee$ (C:\\Users\\91809\\Desktop\\MyFirstProject\\src\\config\\/database.js:12:20)\n    at tryCatch (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:86:17)\n    at Generator._invoke (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:66:24)\n    at Generator.next (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:117:21)\n    at asyncGeneratorStep (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:3:24)\n    at _next (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:25:9)\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:32:7\n    at new Promise (<anonymous>)\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:21:12","timestamp":"2022-05-25T04:15:25.884Z"}
error: Could not connect to the database. connect ECONNREFUSED ::1:27017 {"reason":{"commonWireVersion":null,"compatibilityError":null,"compatible":true,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"logicalSessionTimeoutMinutes":null,"maxElectionId":null,"maxSetVersion":null,"servers":{},"setName":null,"stale":false,"type":"Single"},"stack":"MongooseServerSelectionError: connect ECONNREFUSED ::1:27017\n    at NativeConnection.Connection.openUri (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\connection.js:847:32)\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\index.js:351:10\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:32:5\n    at new Promise (<anonymous>)\n    at promiseOrCallback (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:31:10)\n    at Mongoose._promiseOrCallback (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\index.js:1149:10)\n    at Mongoose.connect (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\index.js:350:20)\n    at _callee$ (C:\\Users\\91809\\Desktop\\MyFirstProject\\src\\config\\/database.js:12:20)\n    at tryCatch (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:86:17)\n    at Generator._invoke (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:66:24)\n    at Generator.next (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:117:21)\n    at asyncGeneratorStep (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:3:24)\n    at _next (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:25:9)\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:32:7\n    at new Promise (<anonymous>)\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:21:12","timestamp":"2022-05-25T04:19:35.828Z"}
error: Could not connect to the database. connect ECONNREFUSED ::1:27017 {"reason":{"commonWireVersion":null,"compatibilityError":null,"compatible":true,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"logicalSessionTimeoutMinutes":null,"maxElectionId":null,"maxSetVersion":null,"servers":{},"setName":null,"stale":false,"type":"Single"},"stack":"MongooseServerSelectionError: connect ECONNREFUSED ::1:27017\n    at NativeConnection.Connection.openUri (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\connection.js:847:32)\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\index.js:351:10\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:32:5\n    at new Promise (<anonymous>)\n    at promiseOrCallback (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:31:10)\n    at Mongoose._promiseOrCallback (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\index.js:1149:10)\n    at Mongoose.connect (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\index.js:350:20)\n    at _callee$ (C:\\Users\\91809\\Desktop\\MyFirstProject\\src\\config\\/database.js:12:20)\n    at tryCatch (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:86:17)\n    at Generator._invoke (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:66:24)\n    at Generator.next (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:117:21)\n    at asyncGeneratorStep (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:3:24)\n    at _next (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:25:9)\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:32:7\n    at new Promise (<anonymous>)\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:21:12","timestamp":"2022-05-25T04:22:53.804Z"}
error: Could not connect to the database. connect ECONNREFUSED ::1:27017 {"reason":{"commonWireVersion":null,"compatibilityError":null,"compatible":true,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"logicalSessionTimeoutMinutes":null,"maxElectionId":null,"maxSetVersion":null,"servers":{},"setName":null,"stale":false,"type":"Single"},"stack":"MongooseServerSelectionError: connect ECONNREFUSED ::1:27017\n    at NativeConnection.Connection.openUri (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\connection.js:847:32)\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\index.js:351:10\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:32:5\n    at new Promise (<anonymous>)\n    at promiseOrCallback (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:31:10)\n    at Mongoose._promiseOrCallback (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\index.js:1149:10)\n    at Mongoose.connect (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\index.js:350:20)\n    at _callee$ (C:\\Users\\91809\\Desktop\\MyFirstProject\\src\\config\\/database.js:12:20)\n    at tryCatch (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:86:17)\n    at Generator._invoke (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:66:24)\n    at Generator.next (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:117:21)\n    at asyncGeneratorStep (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:3:24)\n    at _next (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:25:9)\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:32:7\n    at new Promise (<anonymous>)\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:21:12","timestamp":"2022-05-25T05:59:10.576Z"}
error: Could not connect to the database. connect ECONNREFUSED ::1:27017 {"reason":{"commonWireVersion":null,"compatibilityError":null,"compatible":true,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"logicalSessionTimeoutMinutes":null,"maxElectionId":null,"maxSetVersion":null,"servers":{},"setName":null,"stale":false,"type":"Single"},"stack":"MongooseServerSelectionError: connect ECONNREFUSED ::1:27017\n    at NativeConnection.Connection.openUri (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\connection.js:847:32)\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\index.js:351:10\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:32:5\n    at new Promise (<anonymous>)\n    at promiseOrCallback (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:31:10)\n    at Mongoose._promiseOrCallback (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\index.js:1149:10)\n    at Mongoose.connect (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\index.js:350:20)\n    at _callee$ (C:\\Users\\91809\\Desktop\\MyFirstProject\\src\\config\\/database.js:12:20)\n    at tryCatch (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:86:17)\n    at Generator._invoke (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:66:24)\n    at Generator.next (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:117:21)\n    at asyncGeneratorStep (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:3:24)\n    at _next (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:25:9)\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:32:7\n    at new Promise (<anonymous>)\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:21:12","timestamp":"2022-05-25T06:00:52.012Z"}
error: Could not connect to the database. connect ECONNREFUSED ::1:27017 {"reason":{"commonWireVersion":null,"compatibilityError":null,"compatible":true,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"logicalSessionTimeoutMinutes":null,"maxElectionId":null,"maxSetVersion":null,"servers":{},"setName":null,"stale":false,"type":"Single"},"stack":"MongooseServerSelectionError: connect ECONNREFUSED ::1:27017\n    at NativeConnection.Connection.openUri (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\connection.js:847:32)\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\index.js:351:10\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:32:5\n    at new Promise (<anonymous>)\n    at promiseOrCallback (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:31:10)\n    at Mongoose._promiseOrCallback (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\index.js:1149:10)\n    at Mongoose.connect (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\index.js:350:20)\n    at _callee$ (C:\\Users\\91809\\Desktop\\MyFirstProject\\src\\config\\/database.js:12:20)\n    at tryCatch (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:86:17)\n    at Generator._invoke (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:66:24)\n    at Generator.next (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:117:21)\n    at asyncGeneratorStep (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:3:24)\n    at _next (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:25:9)\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:32:7\n    at new Promise (<anonymous>)\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:21:12","timestamp":"2022-05-25T06:04:17.871Z"}
error: Could not connect to the database. connect ECONNREFUSED ::1:27017 {"reason":{"commonWireVersion":null,"compatibilityError":null,"compatible":true,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"logicalSessionTimeoutMinutes":null,"maxElectionId":null,"maxSetVersion":null,"servers":{},"setName":null,"stale":false,"type":"Single"},"stack":"MongooseServerSelectionError: connect ECONNREFUSED ::1:27017\n    at NativeConnection.Connection.openUri (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\connection.js:847:32)\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\index.js:351:10\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:32:5\n    at new Promise (<anonymous>)\n    at promiseOrCallback (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:31:10)\n    at Mongoose._promiseOrCallback (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\index.js:1149:10)\n    at Mongoose.connect (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\index.js:350:20)\n    at _callee$ (C:\\Users\\91809\\Desktop\\MyFirstProject\\src\\config\\/database.js:12:20)\n    at tryCatch (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:86:17)\n    at Generator._invoke (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:66:24)\n    at Generator.next (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:117:21)\n    at asyncGeneratorStep (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:3:24)\n    at _next (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:25:9)\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:32:7\n    at new Promise (<anonymous>)\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:21:12","timestamp":"2022-05-25T06:05:47.469Z"}
error: Could not connect to the database. connect ECONNREFUSED ::1:27017 {"reason":{"commonWireVersion":null,"compatibilityError":null,"compatible":true,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"logicalSessionTimeoutMinutes":null,"maxElectionId":null,"maxSetVersion":null,"servers":{},"setName":null,"stale":false,"type":"Single"},"stack":"MongooseServerSelectionError: connect ECONNREFUSED ::1:27017\n    at NativeConnection.Connection.openUri (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\connection.js:847:32)\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\index.js:351:10\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:32:5\n    at new Promise (<anonymous>)\n    at promiseOrCallback (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:31:10)\n    at Mongoose._promiseOrCallback (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\index.js:1149:10)\n    at Mongoose.connect (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\index.js:350:20)\n    at _callee$ (C:\\Users\\91809\\Desktop\\MyFirstProject\\src\\config\\/database.js:12:20)\n    at tryCatch (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:86:17)\n    at Generator._invoke (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:66:24)\n    at Generator.next (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:117:21)\n    at asyncGeneratorStep (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:3:24)\n    at _next (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:25:9)\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:32:7\n    at new Promise (<anonymous>)\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:21:12","timestamp":"2022-05-25T06:07:22.833Z"}
error: 
    status - 500 
    message - MongooseError: Operation `users.insertOne()` buffering timed out after 10000ms
    at Timeout.<anonymous> (C:\Users\91809\Desktop\MyFirstProject\node_modules\mongoose\lib\drivers\node-mongodb-native\collection.js:198:23)
    at listOnTimeout (node:internal/timers:564:17)
    at processTimers (node:internal/timers:507:7) 
    url - /api/v1/users 
    method - POST 
    IP - ::1
   {"timestamp":"2022-05-25T06:07:23.496Z"}
error: Could not connect to the database. connect ECONNREFUSED ::1:27017 {"reason":{"commonWireVersion":null,"compatibilityError":null,"compatible":true,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"logicalSessionTimeoutMinutes":null,"maxElectionId":null,"maxSetVersion":null,"servers":{},"setName":null,"stale":false,"type":"Single"},"stack":"MongooseServerSelectionError: connect ECONNREFUSED ::1:27017\n    at NativeConnection.Connection.openUri (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\connection.js:847:32)\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\index.js:351:10\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:32:5\n    at new Promise (<anonymous>)\n    at promiseOrCallback (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:31:10)\n    at Mongoose._promiseOrCallback (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\index.js:1149:10)\n    at Mongoose.connect (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\index.js:350:20)\n    at _callee$ (C:\\Users\\91809\\Desktop\\MyFirstProject\\src\\config\\/database.js:12:20)\n    at tryCatch (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:86:17)\n    at Generator._invoke (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:66:24)\n    at Generator.next (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:117:21)\n    at asyncGeneratorStep (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:3:24)\n    at _next (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:25:9)\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:32:7\n    at new Promise (<anonymous>)\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:21:12","timestamp":"2022-05-25T06:12:18.323Z"}
error: Could not connect to the database. connect ECONNREFUSED ::1:27017 {"reason":{"commonWireVersion":null,"compatibilityError":null,"compatible":true,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"logicalSessionTimeoutMinutes":null,"maxElectionId":null,"maxSetVersion":null,"servers":{},"setName":null,"stale":false,"type":"Single"},"stack":"MongooseServerSelectionError: connect ECONNREFUSED ::1:27017\n    at NativeConnection.Connection.openUri (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\connection.js:847:32)\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\index.js:351:10\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:32:5\n    at new Promise (<anonymous>)\n    at promiseOrCallback (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:31:10)\n    at Mongoose._promiseOrCallback (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\index.js:1149:10)\n    at Mongoose.connect (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\index.js:350:20)\n    at _callee$ (C:\\Users\\91809\\Desktop\\MyFirstProject\\src\\config\\/database.js:12:20)\n    at tryCatch (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:86:17)\n    at Generator._invoke (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:66:24)\n    at Generator.next (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:117:21)\n    at asyncGeneratorStep (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:3:24)\n    at _next (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:25:9)\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:32:7\n    at new Promise (<anonymous>)\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:21:12","timestamp":"2022-05-25T06:15:09.332Z"}
error: Could not connect to the database. connect ECONNREFUSED ::1:27017 {"reason":{"commonWireVersion":null,"compatibilityError":null,"compatible":true,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"logicalSessionTimeoutMinutes":null,"maxElectionId":null,"maxSetVersion":null,"servers":{},"setName":null,"stale":false,"type":"Single"},"stack":"MongooseServerSelectionError: connect ECONNREFUSED ::1:27017\n    at NativeConnection.Connection.openUri (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\connection.js:847:32)\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\index.js:351:10\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:32:5\n    at new Promise (<anonymous>)\n    at promiseOrCallback (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:31:10)\n    at Mongoose._promiseOrCallback (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\index.js:1149:10)\n    at Mongoose.connect (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\index.js:350:20)\n    at _callee$ (C:\\Users\\91809\\Desktop\\MyFirstProject\\src\\config\\/database.js:12:20)\n    at tryCatch (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:86:17)\n    at Generator._invoke (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:66:24)\n    at Generator.next (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:117:21)\n    at asyncGeneratorStep (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:3:24)\n    at _next (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:25:9)\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:32:7\n    at new Promise (<anonymous>)\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:21:12","timestamp":"2022-05-25T06:22:05.024Z"}
error: Could not connect to the database. connect ECONNREFUSED ::1:27017 {"reason":{"commonWireVersion":null,"compatibilityError":null,"compatible":true,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"logicalSessionTimeoutMinutes":null,"maxElectionId":null,"maxSetVersion":null,"servers":{},"setName":null,"stale":false,"type":"Single"},"stack":"MongooseServerSelectionError: connect ECONNREFUSED ::1:27017\n    at NativeConnection.Connection.openUri (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\connection.js:847:32)\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\index.js:351:10\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:32:5\n    at new Promise (<anonymous>)\n    at promiseOrCallback (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:31:10)\n    at Mongoose._promiseOrCallback (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\index.js:1149:10)\n    at Mongoose.connect (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\index.js:350:20)\n    at _callee$ (C:\\Users\\91809\\Desktop\\MyFirstProject\\src\\config\\/database.js:12:20)\n    at tryCatch (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:86:17)\n    at Generator._invoke (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:66:24)\n    at Generator.next (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:117:21)\n    at asyncGeneratorStep (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:3:24)\n    at _next (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:25:9)\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:32:7\n    at new Promise (<anonymous>)\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:21:12","timestamp":"2022-05-25T06:27:12.243Z"}
error: Could not connect to the database. connect ECONNREFUSED ::1:27017 {"reason":{"commonWireVersion":null,"compatibilityError":null,"compatible":true,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"logicalSessionTimeoutMinutes":null,"maxElectionId":null,"maxSetVersion":null,"servers":{},"setName":null,"stale":false,"type":"Single"},"stack":"MongooseServerSelectionError: connect ECONNREFUSED ::1:27017\n    at NativeConnection.Connection.openUri (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\connection.js:847:32)\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\index.js:351:10\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:32:5\n    at new Promise (<anonymous>)\n    at promiseOrCallback (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:31:10)\n    at Mongoose._promiseOrCallback (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\index.js:1149:10)\n    at Mongoose.connect (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\index.js:350:20)\n    at _callee$ (C:\\Users\\91809\\Desktop\\MyFirstProject\\src\\config\\/database.js:12:20)\n    at tryCatch (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:86:17)\n    at Generator._invoke (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:66:24)\n    at Generator.next (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:117:21)\n    at asyncGeneratorStep (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:3:24)\n    at _next (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:25:9)\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:32:7\n    at new Promise (<anonymous>)\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:21:12","timestamp":"2022-05-25T06:30:31.793Z"}
error: Could not connect to the database. connect ECONNREFUSED ::1:27017 {"reason":{"commonWireVersion":null,"compatibilityError":null,"compatible":true,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"logicalSessionTimeoutMinutes":null,"maxElectionId":null,"maxSetVersion":null,"servers":{},"setName":null,"stale":false,"type":"Single"},"stack":"MongooseServerSelectionError: connect ECONNREFUSED ::1:27017\n    at NativeConnection.Connection.openUri (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\connection.js:847:32)\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\index.js:351:10\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:32:5\n    at new Promise (<anonymous>)\n    at promiseOrCallback (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:31:10)\n    at Mongoose._promiseOrCallback (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\index.js:1149:10)\n    at Mongoose.connect (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\index.js:350:20)\n    at _callee$ (C:\\Users\\91809\\Desktop\\MyFirstProject\\src\\config\\/database.js:12:20)\n    at tryCatch (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:86:17)\n    at Generator._invoke (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:66:24)\n    at Generator.next (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:117:21)\n    at asyncGeneratorStep (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:3:24)\n    at _next (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:25:9)\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:32:7\n    at new Promise (<anonymous>)\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:21:12","timestamp":"2022-05-25T06:32:37.585Z"}
error: Could not connect to the database. connect ECONNREFUSED ::1:27017 {"reason":{"commonWireVersion":null,"compatibilityError":null,"compatible":true,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"logicalSessionTimeoutMinutes":null,"maxElectionId":null,"maxSetVersion":null,"servers":{},"setName":null,"stale":false,"type":"Single"},"stack":"MongooseServerSelectionError: connect ECONNREFUSED ::1:27017\n    at NativeConnection.Connection.openUri (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\connection.js:847:32)\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\index.js:351:10\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:32:5\n    at new Promise (<anonymous>)\n    at promiseOrCallback (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:31:10)\n    at Mongoose._promiseOrCallback (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\index.js:1149:10)\n    at Mongoose.connect (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\index.js:350:20)\n    at _callee$ (C:\\Users\\91809\\Desktop\\MyFirstProject\\src\\config\\/database.js:12:20)\n    at tryCatch (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:86:17)\n    at Generator._invoke (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:66:24)\n    at Generator.next (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:117:21)\n    at asyncGeneratorStep (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:3:24)\n    at _next (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:25:9)\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:32:7\n    at new Promise (<anonymous>)\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:21:12","timestamp":"2022-05-25T06:37:12.120Z"}
error: 
      status - 400
      message - Authorization token is required 
      url - /api/v1/users/628dcf2a7e567213ecbe3b66 
      method - GET 
      IP - ::1
     {"timestamp":"2022-05-25T06:41:15.885Z"}
error: Could not connect to the database. connect ECONNREFUSED ::1:27017 {"reason":{"commonWireVersion":null,"compatibilityError":null,"compatible":true,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"logicalSessionTimeoutMinutes":null,"maxElectionId":null,"maxSetVersion":null,"servers":{},"setName":null,"stale":false,"type":"Single"},"stack":"MongooseServerSelectionError: connect ECONNREFUSED ::1:27017\n    at NativeConnection.Connection.openUri (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\connection.js:847:32)\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\index.js:351:10\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:32:5\n    at new Promise (<anonymous>)\n    at promiseOrCallback (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:31:10)\n    at Mongoose._promiseOrCallback (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\index.js:1149:10)\n    at Mongoose.connect (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\index.js:350:20)\n    at _callee$ (C:\\Users\\91809\\Desktop\\MyFirstProject\\src\\config\\/database.js:12:20)\n    at tryCatch (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:86:17)\n    at Generator._invoke (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:66:24)\n    at Generator.next (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:117:21)\n    at asyncGeneratorStep (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:3:24)\n    at _next (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:25:9)\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:32:7\n    at new Promise (<anonymous>)\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:21:12","timestamp":"2022-05-25T08:54:14.476Z"}
error: Could not connect to the database. connect ECONNREFUSED ::1:27017 {"reason":{"commonWireVersion":null,"compatibilityError":null,"compatible":true,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"logicalSessionTimeoutMinutes":null,"maxElectionId":null,"maxSetVersion":null,"servers":{},"setName":null,"stale":false,"type":"Single"},"stack":"MongooseServerSelectionError: connect ECONNREFUSED ::1:27017\n    at NativeConnection.Connection.openUri (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\connection.js:847:32)\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\index.js:351:10\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:32:5\n    at new Promise (<anonymous>)\n    at promiseOrCallback (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:31:10)\n    at Mongoose._promiseOrCallback (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\index.js:1149:10)\n    at Mongoose.connect (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\index.js:350:20)\n    at _callee$ (C:\\Users\\91809\\Desktop\\MyFirstProject\\src\\config\\/database.js:12:20)\n    at tryCatch (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:86:17)\n    at Generator._invoke (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:66:24)\n    at Generator.next (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:117:21)\n    at asyncGeneratorStep (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:3:24)\n    at _next (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:25:9)\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:32:7\n    at new Promise (<anonymous>)\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:21:12","timestamp":"2022-05-25T09:16:03.616Z"}
error: Could not connect to the database. connect ECONNREFUSED ::1:27017 {"reason":{"commonWireVersion":null,"compatibilityError":null,"compatible":true,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"logicalSessionTimeoutMinutes":null,"maxElectionId":null,"maxSetVersion":null,"servers":{},"setName":null,"stale":false,"type":"Single"},"stack":"MongooseServerSelectionError: connect ECONNREFUSED ::1:27017\n    at NativeConnection.Connection.openUri (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\connection.js:847:32)\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\index.js:351:10\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:32:5\n    at new Promise (<anonymous>)\n    at promiseOrCallback (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:31:10)\n    at Mongoose._promiseOrCallback (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\index.js:1149:10)\n    at Mongoose.connect (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\index.js:350:20)\n    at _callee$ (C:\\Users\\91809\\Desktop\\MyFirstProject\\src\\config\\/database.js:12:20)\n    at tryCatch (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:86:17)\n    at Generator._invoke (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:66:24)\n    at Generator.next (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:117:21)\n    at asyncGeneratorStep (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:3:24)\n    at _next (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:25:9)\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:32:7\n    at new Promise (<anonymous>)\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:21:12","timestamp":"2022-05-25T09:36:09.394Z"}
error: Could not connect to the database. connect ECONNREFUSED ::1:27017 {"reason":{"commonWireVersion":null,"compatibilityError":null,"compatible":true,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"logicalSessionTimeoutMinutes":null,"maxElectionId":null,"maxSetVersion":null,"servers":{},"setName":null,"stale":false,"type":"Single"},"stack":"MongooseServerSelectionError: connect ECONNREFUSED ::1:27017\n    at NativeConnection.Connection.openUri (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\connection.js:847:32)\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\index.js:351:10\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:32:5\n    at new Promise (<anonymous>)\n    at promiseOrCallback (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:31:10)\n    at Mongoose._promiseOrCallback (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\index.js:1149:10)\n    at Mongoose.connect (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\index.js:350:20)\n    at _callee$ (C:\\Users\\91809\\Desktop\\MyFirstProject\\src\\config\\/database.js:12:20)\n    at tryCatch (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:86:17)\n    at Generator._invoke (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:66:24)\n    at Generator.next (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:117:21)\n    at asyncGeneratorStep (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:3:24)\n    at _next (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:25:9)\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:32:7\n    at new Promise (<anonymous>)\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:21:12","timestamp":"2022-05-25T09:54:54.078Z"}
error: Could not connect to the database. connect ECONNREFUSED ::1:27017 {"reason":{"commonWireVersion":null,"compatibilityError":null,"compatible":true,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"logicalSessionTimeoutMinutes":null,"maxElectionId":null,"maxSetVersion":null,"servers":{},"setName":null,"stale":false,"type":"Single"},"stack":"MongooseServerSelectionError: connect ECONNREFUSED ::1:27017\n    at NativeConnection.Connection.openUri (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\connection.js:847:32)\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\index.js:351:10\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:32:5\n    at new Promise (<anonymous>)\n    at promiseOrCallback (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:31:10)\n    at Mongoose._promiseOrCallback (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\index.js:1149:10)\n    at Mongoose.connect (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\index.js:350:20)\n    at _callee$ (C:\\Users\\91809\\Desktop\\MyFirstProject\\src\\config\\/database.js:12:20)\n    at tryCatch (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:86:17)\n    at Generator._invoke (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:66:24)\n    at Generator.next (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:117:21)\n    at asyncGeneratorStep (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:3:24)\n    at _next (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:25:9)\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:32:7\n    at new Promise (<anonymous>)\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:21:12","timestamp":"2022-05-25T10:21:29.503Z"}
error: Could not connect to the database. connect ECONNREFUSED ::1:27017 {"reason":{"commonWireVersion":null,"compatibilityError":null,"compatible":true,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"logicalSessionTimeoutMinutes":null,"maxElectionId":null,"maxSetVersion":null,"servers":{},"setName":null,"stale":false,"type":"Single"},"stack":"MongooseServerSelectionError: connect ECONNREFUSED ::1:27017\n    at NativeConnection.Connection.openUri (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\connection.js:847:32)\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\index.js:351:10\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:32:5\n    at new Promise (<anonymous>)\n    at promiseOrCallback (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:31:10)\n    at Mongoose._promiseOrCallback (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\index.js:1149:10)\n    at Mongoose.connect (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\index.js:350:20)\n    at _callee$ (C:\\Users\\91809\\Desktop\\MyFirstProject\\src\\config\\/database.js:12:20)\n    at tryCatch (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:86:17)\n    at Generator._invoke (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:66:24)\n    at Generator.next (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:117:21)\n    at asyncGeneratorStep (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:3:24)\n    at _next (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:25:9)\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:32:7\n    at new Promise (<anonymous>)\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:21:12","timestamp":"2022-05-25T10:24:01.478Z"}
error: Could not connect to the database. connect ECONNREFUSED ::1:27017 {"reason":{"commonWireVersion":null,"compatibilityError":null,"compatible":true,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"logicalSessionTimeoutMinutes":null,"maxElectionId":null,"maxSetVersion":null,"servers":{},"setName":null,"stale":false,"type":"Single"},"stack":"MongooseServerSelectionError: connect ECONNREFUSED ::1:27017\n    at NativeConnection.Connection.openUri (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\connection.js:847:32)\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\index.js:351:10\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:32:5\n    at new Promise (<anonymous>)\n    at promiseOrCallback (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:31:10)\n    at Mongoose._promiseOrCallback (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\index.js:1149:10)\n    at Mongoose.connect (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\index.js:350:20)\n    at _callee$ (C:\\Users\\91809\\Desktop\\MyFirstProject\\src\\config\\/database.js:12:20)\n    at tryCatch (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:86:17)\n    at Generator._invoke (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:66:24)\n    at Generator.next (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:117:21)\n    at asyncGeneratorStep (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:3:24)\n    at _next (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:25:9)\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:32:7\n    at new Promise (<anonymous>)\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:21:12","timestamp":"2022-05-25T10:37:05.125Z"}
error: Could not connect to the database. connect ECONNREFUSED ::1:27017 {"reason":{"commonWireVersion":null,"compatibilityError":null,"compatible":true,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"logicalSessionTimeoutMinutes":null,"maxElectionId":null,"maxSetVersion":null,"servers":{},"setName":null,"stale":false,"type":"Single"},"stack":"MongooseServerSelectionError: connect ECONNREFUSED ::1:27017\n    at NativeConnection.Connection.openUri (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\connection.js:847:32)\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\index.js:351:10\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:32:5\n    at new Promise (<anonymous>)\n    at promiseOrCallback (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:31:10)\n    at Mongoose._promiseOrCallback (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\index.js:1149:10)\n    at Mongoose.connect (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\index.js:350:20)\n    at _callee$ (C:\\Users\\91809\\Desktop\\MyFirstProject\\src\\config\\/database.js:12:20)\n    at tryCatch (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:86:17)\n    at Generator._invoke (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:66:24)\n    at Generator.next (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:117:21)\n    at asyncGeneratorStep (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:3:24)\n    at _next (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:25:9)\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:32:7\n    at new Promise (<anonymous>)\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:21:12","timestamp":"2022-05-25T10:38:31.500Z"}
error: Could not connect to the database. connect ECONNREFUSED ::1:27017 {"reason":{"commonWireVersion":null,"compatibilityError":null,"compatible":true,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"logicalSessionTimeoutMinutes":null,"maxElectionId":null,"maxSetVersion":null,"servers":{},"setName":null,"stale":false,"type":"Single"},"stack":"MongooseServerSelectionError: connect ECONNREFUSED ::1:27017\n    at NativeConnection.Connection.openUri (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\connection.js:847:32)\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\index.js:351:10\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:32:5\n    at new Promise (<anonymous>)\n    at promiseOrCallback (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:31:10)\n    at Mongoose._promiseOrCallback (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\index.js:1149:10)\n    at Mongoose.connect (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\index.js:350:20)\n    at _callee$ (C:\\Users\\91809\\Desktop\\MyFirstProject\\src\\config\\/database.js:12:20)\n    at tryCatch (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:86:17)\n    at Generator._invoke (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:66:24)\n    at Generator.next (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:117:21)\n    at asyncGeneratorStep (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:3:24)\n    at _next (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:25:9)\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:32:7\n    at new Promise (<anonymous>)\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:21:12","timestamp":"2022-05-25T10:47:28.503Z"}
error: Could not connect to the database. connect ECONNREFUSED ::1:27017 {"reason":{"commonWireVersion":null,"compatibilityError":null,"compatible":true,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"logicalSessionTimeoutMinutes":null,"maxElectionId":null,"maxSetVersion":null,"servers":{},"setName":null,"stale":false,"type":"Single"},"stack":"MongooseServerSelectionError: connect ECONNREFUSED ::1:27017\n    at NativeConnection.Connection.openUri (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\connection.js:847:32)\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\index.js:351:10\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:32:5\n    at new Promise (<anonymous>)\n    at promiseOrCallback (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:31:10)\n    at Mongoose._promiseOrCallback (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\index.js:1149:10)\n    at Mongoose.connect (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\index.js:350:20)\n    at _callee$ (C:\\Users\\91809\\Desktop\\MyFirstProject\\src\\config\\/database.js:12:20)\n    at tryCatch (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:86:17)\n    at Generator._invoke (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:66:24)\n    at Generator.next (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:117:21)\n    at asyncGeneratorStep (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:3:24)\n    at _next (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:25:9)\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:32:7\n    at new Promise (<anonymous>)\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:21:12","timestamp":"2022-05-25T10:56:03.572Z"}
error: 
    status - 500 
    message - MongooseError: Operation `users.findOneAndUpdate()` buffering timed out after 10000ms
    at Timeout.<anonymous> (C:\Users\91809\Desktop\MyFirstProject\node_modules\mongoose\lib\drivers\node-mongodb-native\collection.js:198:23)
    at listOnTimeout (node:internal/timers:564:17)
    at processTimers (node:internal/timers:507:7) 
    url - /api/v1/users/628e0a3d2ee2641c147c3bc2 
    method - PUT 
    IP - ::1
   {"timestamp":"2022-05-25T10:58:19.422Z"}
error: Could not connect to the database. connect ECONNREFUSED ::1:27017 {"reason":{"commonWireVersion":null,"compatibilityError":null,"compatible":true,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"logicalSessionTimeoutMinutes":null,"maxElectionId":null,"maxSetVersion":null,"servers":{},"setName":null,"stale":false,"type":"Single"},"stack":"MongooseServerSelectionError: connect ECONNREFUSED ::1:27017\n    at NativeConnection.Connection.openUri (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\connection.js:847:32)\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\index.js:351:10\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:32:5\n    at new Promise (<anonymous>)\n    at promiseOrCallback (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:31:10)\n    at Mongoose._promiseOrCallback (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\index.js:1149:10)\n    at Mongoose.connect (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\index.js:350:20)\n    at _callee$ (C:\\Users\\91809\\Desktop\\MyFirstProject\\src\\config\\/database.js:12:20)\n    at tryCatch (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:86:17)\n    at Generator._invoke (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:66:24)\n    at Generator.next (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:117:21)\n    at asyncGeneratorStep (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:3:24)\n    at _next (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:25:9)\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:32:7\n    at new Promise (<anonymous>)\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:21:12","timestamp":"2022-05-25T10:58:24.392Z"}
error: 
    status - 500 
    message - MongooseError: Operation `users.findOneAndUpdate()` buffering timed out after 10000ms
    at Timeout.<anonymous> (C:\Users\91809\Desktop\MyFirstProject\node_modules\mongoose\lib\drivers\node-mongodb-native\collection.js:198:23)
    at listOnTimeout (node:internal/timers:564:17)
    at processTimers (node:internal/timers:507:7) 
    url - /api/v1/users/628e0a3d2ee2641c147c3bc2 
    method - PUT 
    IP - ::1
   {"timestamp":"2022-05-25T10:58:55.053Z"}
error: 
      status - 400
      message - Authorization token is required 
      url - /api/v1/users/628dcf187e567213ecbe3b64 
      method - GET 
      IP - ::1
     {"timestamp":"2022-05-25T11:03:09.094Z"}
error: Could not connect to the database. connect ECONNREFUSED ::1:27017 {"reason":{"commonWireVersion":null,"compatibilityError":null,"compatible":true,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"logicalSessionTimeoutMinutes":null,"maxElectionId":null,"maxSetVersion":null,"servers":{},"setName":null,"stale":false,"type":"Single"},"stack":"MongooseServerSelectionError: connect ECONNREFUSED ::1:27017\n    at NativeConnection.Connection.openUri (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\connection.js:847:32)\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\index.js:351:10\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:32:5\n    at new Promise (<anonymous>)\n    at promiseOrCallback (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:31:10)\n    at Mongoose._promiseOrCallback (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\index.js:1149:10)\n    at Mongoose.connect (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\mongoose\\lib\\index.js:350:20)\n    at _callee$ (C:\\Users\\91809\\Desktop\\MyFirstProject\\src\\config\\/database.js:12:20)\n    at tryCatch (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:86:17)\n    at Generator._invoke (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:66:24)\n    at Generator.next (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:117:21)\n    at asyncGeneratorStep (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:3:24)\n    at _next (C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:25:9)\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:32:7\n    at new Promise (<anonymous>)\n    at C:\\Users\\91809\\Desktop\\MyFirstProject\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:21:12","timestamp":"2022-05-25T11:42:20.576Z"}
error: 
      status - 400
      message - Authorization token is required 
      url - /api/v1/users/628dcf187e567213ecbe3b64 
      method - GET 
      IP - ::1
     {"timestamp":"2022-05-26T02:24:22.362Z"}
error: 
      status - 400
      message - Authorization token is required 
      url - /api/v1/users/628eea450fa00621a44167e0 
      method - GET 
      IP - ::1
     {"timestamp":"2022-05-26T02:48:52.843Z"}
